### ISSUE TITLE
Can't connect to any peer

### ISSUE THREAD

**Issue by fwhappy** [axieinfinity/ronin#236]
After a long time, still can't connect to any peer

`ronin --datadir=/ronin/data --networkid 2020 --bootnodes enode://62a6c6d483bbebe9e2e2c9abd6e053bf81b7ce8662defd40f6ee32665a83dbfaf1fe32e6855efde06e04d6f2d7ce8ad411ef7fc77b48d95134b3cb9b505e2058@34.66.90.95:30303,enode://62a6c6d483bbebe9e2e2c9abd6e053bf81b7ce8662defd40f6ee32665a83dbfaf1fe32e6855efde06e04d6f2d7ce8ad411ef7fc77b48d95134b3cb9b505e2058@104.198.242.88:30303,enode://62a6c6d483bbebe9e2e2c9abd6e053bf81b7ce8662defd40f6ee32665a83dbfaf1fe32e6855efde06e04d6f2d7ce8ad411ef7fc77b48d95134b3cb9b505e2058@34.132.30.191:30303 --port 30303 --http --http.corsdomain '*' --http.addr 0.0.0.0 --http.port 8545 --http.vhosts '*' --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins '*'`

Logs:
INFO [03-13|06:14:22.406] HTTP server started                      endpoint=[::]:8545 prefix= cors='*' vhosts='*'
INFO [03-13|06:14:22.406] WebSocket enabled                        url=ws://[::]:8546
INFO [03-13|06:14:22.506] Generated state snapshot                 accounts=8893 slots=0 storage=409.64KiB elapsed=112.778ms
INFO [03-13|06:14:24.947] New local node record                    seq=1,678,688,062,404 id=6a001edb7d43afb5 ip=3.69.231.16 udp=30303 tcp=30303
INFO [03-13|06:14:32.440] Looking for peers                        peercount=1 tried=126 static=0
INFO [03-13|06:14:42.864] Looking for peers                        peercount=0 tried=78  static=0
INFO [03-13|06:14:52.976] Looking for peers                        peercount=1 tried=129 static=0
INFO [03-13|06:15:02.994] Looking for peers                        peercount=1 tried=156 static=0
INFO [03-13|06:15:13.001] Looking for peers                        peercount=0 tried=177 static=0
INFO [03-13|06:15:23.003] Looking for peers                        peercount=0 tried=173 static=0
INFO [03-13|06:15:33.420] Looking for peers                        peercount=0 tried=131 static=0
ERROR[03-13|06:15:39.596] Snapshot extension registration failed   peer=8813746d err="peer connected on snap without compatible eth support"
INFO [03-13|06:15:43.519] Looking for peers                        peercount=0 tried=206 static=0
INFO [03-13|06:15:53.527] Looking for peers                        peercount=2 tried=41  static=0
INFO [03-13|06:16:03.535] Looking for peers                        peercount=0 tried=218 static=0
INFO [03-13|06:16:13.542] Looking for peers                        peercount=0 tried=110 static=0
ERROR[03-13|06:16:14.942] Snapshot extension registration failed   peer=bcbefcff err="peer connected on snap without compatible eth support"
INFO [03-13|06:16:23.754] Looking for peers                        peercount=0 tried=127 static=0
INFO [03-13|06:16:33.762] Looking for peers                        peercount=2 tried=172 static=0
INFO [03-13|06:16:43.935] Looking for peers                        peercount=1 tried=163 static=0
INFO [03-13|06:16:53.952] Looking for peers                        peercount=1 tried=164 static=0
ERROR[03-13|06:16:57.747] Snapshot extension registration failed   peer=b3b03e49 err="peer connected on snap without compatible eth support"
INFO [03-13|06:17:05.814] Looking for peers                        peercount=0 tried=170 static=0
INFO [03-13|06:17:15.851] Looking for peers                        peercount=1 tried=111 static=0
INFO [03-13|06:17:26.037] Looking for peers                        peercount=0 tried=201 static=0
INFO [03-13|06:17:46.442] Looking for peers                        peercount=0 tried=178 static=0
INFO [03-13|06:17:56.444] Looking for peers                        peercount=0 tried=195 static=0
INFO [03-13|06:18:06.641] Looking for peers                        peercount=1 tried=115 static=0
ERROR[03-13|06:18:08.915] Snapshot extension registration failed   peer=63cbe74f err="peer connected on snap without compatible eth support"
ERROR[03-13|06:18:09.651] Snapshot extension registration failed   peer=63b71335 err="peer connected on snap without compatible eth support"
ERROR[03-13|06:18:14.549] Snapshot extension registration failed   peer=2da2309e err="peer connected on snap without compatible eth support"
INFO [03-13|06:18:16.853] Looking for peers                        peercount=0 tried=196 static=0
INFO [03-13|06:18:27.527] Looking for peers                        peercount=0 tried=110 static=0
INFO [03-13|06:18:37.536] Looking for peers                        peercount=0 tried=191 static=0
INFO [03-13|06:18:47.881] Looking for peers                        peercount=0 tried=115 static=0
INFO [03-13|06:18:58.026] Looking for peers                        peercount=0 tried=83  static=0
INFO [03-13|06:19:08.030] Looking for peers                        peercount=0 tried=108 static=0

**Comment by harryngo94** [comment]
Hi ! 
Could u use the new bootnodes enode://cfa5f00c55eba79f359c9d95f5c0b2bb8e173867ffbb6e212c6799a52918502519e56650970e34caf1cd17418d4da46c3243588578886c3b4f8c42d1934bf108@104.198.242.88:30303,enode://f500391c41906a1dae249df084a3d1659fe602db671730b2778316114a5f7df44a0c6864a8dfffdc380fc81c6965dd911338e0e2591eb78a506857015d166250@34.135.18.26:30303,enode://fc7b8ceafe16e6f79ab2da3e73d0a3163d0c28efe0778863102f8f27758986fe28c1540a9a0bbdff29ab93ad1c5803462efe6c98165bbb404d9d099a55f1d2c9@130.211.208.201:30303

**Comment by huyngopt1994** [comment]
Hi !
Could u use the new bootnodes enode://cfa5f00c55eba79f359c9d95f5c0b2bb8e173867ffbb6e212c6799a52918502519e56650970e34caf1cd17418d4da46c3243588578886c3b4f8c42d1934bf108@104.198.242.88:30303,enode://f500391c41906a1dae249df084a3d1659fe602db671730b2778316114a5f7df44a0c6864a8dfffdc380fc81c6965dd911338e0e2591eb78a506857015d166250@34.135.18.26:30303,enode://fc7b8ceafe16e6f79ab2da3e73d0a3163d0c28efe0778863102f8f27758986fe28c1540a9a0bbdff29ab93ad1c5803462efe6c98165bbb404d9d099a55f1d2c9@130.211.208.201:30303

**Comment by fwhappy** [comment]
@thuchoskym 

The network is ok, but still can't connect.

$ telnet 104.198.242.88 30303
Trying 104.198.242.88...
Connected to 104.198.242.88.
Escape character is '^]'.

**Comment by DNK90** [comment]
@fwhappy 
It seems you didn't run init genesis before start peering.
Please run it first
`ronin init mainnet.json --datadir /ronin/data`

The mainnet genesis is missing DPOS configuration, therefore it might be panic when you use the original one. Please use this instead

```
{
  "config": {
    "chainId": 2020,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 4977778,
    "odysseusBlock": 10301597,
    "blacklistContractAddress": "0x313b24994c93FA0471CB4D7aB796b07467041806",
    "fenixBlock": 14938103,
    "fenixValidatorContractAddress": "0x7f13232Bdc3a010c3f749a1c25bF99f1C053CE70",
    "consortiumV2Block": 11706000000000000000000000000000000,
    "consortiumV2Contracts": {
      "roninValidatorSet": "0x54B3AC74a90E64E8dDE60671b6fE8F8DDf18eC9d",
      "slashIndicator": "0xF7837778b6E180Df6696C8Fa986d62f8b6186752",
      "stakingContract": "0x9C245671791834daf3885533D24dce516B763B28"
    },
    "consortium": {
      "period": 3,
      "epoch": 600
    }
  },
  "alloc": {
    "0x0000000000000000000000000000000000000011": {
      "balance": "0x0",
      "code": "0x608060405234801561001057600080fd5b50600436106100a95760003560e01c80636a0cd1f5116100715780636a0cd1f514610160578063b7ab4db51461018c578063c370b042146101e4578063dafae408146101ec578063facd743b1461021d578063fc81975014610243576100a9565b80630f43a677146100ae57806335aa2e44146100c85780634b561753146101015780634e70b1dc1461012f57806353727d2614610137575b600080fd5b6100b661024b565b60408051918252519081900360200190f35b6100e5600480360360208110156100de57600080fd5b5035610251565b604080516001600160a01b039092168252519081900360200190f35b61012d6004803603604081101561011757600080fd5b50803590602001356001600160a01b0316610278565b005b6100b6610408565b61012d6004803603606081101561014d57600080fd5b508035906020810135906040013561040e565b61012d6004803603604081101561017657600080fd5b50803590602001356001600160a01b03166105a4565b610194610743565b60408051602080825283518183015283519192839290830191858101910280838360005b838110156101d05781810151838201526020016101b8565b505050509050019250505060405180910390f35b6100b66107a5565b6102096004803603602081101561020257600080fd5b50356107ab565b604080519115158252519081900360200190f35b6102096004803603602081101561023357600080fd5b50356001600160a01b03166107e0565b6100e56107fe565b60025481565b6001818154811061025e57fe5b6000918252602090912001546001600160a01b0316905081565b610281336107e0565b61028a57600080fd5b604080516001600160a01b03808416828401526020808301849052600c60608401526b30b2322b30b634b230ba37b960a11b6080808501919091528451808503909101815260a09093019093528151919092012060055490916000911663ec9ab83c6102f461080d565b8685336040518563ffffffff1660e01b81526004018080602001858152602001848152602001836001600160a01b03166001600160a01b03168152602001828103825286818151815260200191508051906020019080838360005b8381101561036757818101518382015260200161034f565b50505050905090810190601f1680156103945780820380516001836020036101000a031916815260200191505b5095505050505050602060405180830381600087803b1580156103b657600080fd5b505af11580156103ca573d6000803e3d6000fd5b505050506040513d60208110156103e057600080fd5b5051905060018160028111156103f257fe5b1415610402576104028484610944565b50505050565b60035481565b610417336107e0565b61042057600080fd5b604080518082018490526060808201849052602080830191909152600c60808301526b75706461746551756f72756d60a01b60a0808401919091528351808403909101815260c090920190925280519101206005546000906001600160a01b031663ec9ab83c61048e61080d565b8785336040518563ffffffff1660e01b81526004018080602001858152602001848152602001836001600160a01b03166001600160a01b03168152602001828103825286818151815260200191508051906020019080838360005b838110156105015781810151838201526020016104e9565b50505050905090810190601f16801561052e5780820380516001836020036101000a031916815260200191505b5095505050505050602060405180830381600087803b15801561055057600080fd5b505af1158015610564573d6000803e3d6000fd5b505050506040513d602081101561057a57600080fd5b50519050600181600281111561058c57fe5b141561059d5761059d858585610a02565b5050505050565b6105ad336107e0565b6105b657600080fd5b6105bf816107e0565b6105c857600080fd5b604080516001600160a01b03808416828401526020808301849052600f60608401526e3932b6b7bb32ab30b634b230ba37b960891b6080808501919091528451808503909101815260a09093019093528151919092012060055490916000911663ec9ab83c61063561080d565b8685336040518563ffffffff1660e01b81526004018080602001858152602001848152602001836001600160a01b03166001600160a01b03168152602001828103825286818151815260200191508051906020019080838360005b838110156106a8578181015183820152602001610690565b50505050905090810190601f1680156106d55780820380516001836020036101000a031916815260200191505b5095505050505050602060405180830381600087803b1580156106f757600080fd5b505af115801561070b573d6000803e3d6000fd5b505050506040513d602081101561072157600080fd5b50519050600181600281111561073357fe5b1415610402576104028484610a69565b6060600180548060200260200160405190810160405280929190818152602001828054801561079b57602002820191906000526020600020905b81546001600160a01b0316815260019091019060200180831161077d575b5050505050905090565b60045481565b60006107c4600254600354610bc890919063ffffffff16565b6004546107d890849063ffffffff610bc816565b101592915050565b6001600160a01b031660009081526020819052604090205460ff1690565b6005546001600160a01b031681565b60055460408051638e46684960e01b815290516060926001600160a01b031691638e466849916004808301926000929190829003018186803b15801561085257600080fd5b505afa158015610866573d6000803e3d6000fd5b505050506040513d6000823e601f3d908101601f19168201604052602081101561088f57600080fd5b81019080805160405193929190846401000000008211156108af57600080fd5b9083019060208201858111156108c457600080fd5b82516401000000008111828201881017156108de57600080fd5b82525081516020918201929091019080838360005b8381101561090b5781810151838201526020016108f3565b50505050905090810190601f1680156109385780820380516001836020036101000a031916815260200191505b50604052505050905090565b6001600160a01b03811660009081526020819052604090205460ff161561096a57600080fd5b6001805480820182557fb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf60180546001600160a01b0319166001600160a01b038416908117909155600081815260208190526040808220805460ff191685179055600280549094019093559151909184917f7429a06e9412e469f0d64f9d222640b0af359f556b709e2913588c227851b88d9190a35050565b80821115610a0f57600080fd5b600380546004805492859055839055604080518281526020810184905281519293928592879289927f976f8a9c5bdf8248dec172376d6e2b80a8e3df2f0328e381c6db8e1cf138c0f8929181900390910190a45050505050565b610a72816107e0565b610a7b57600080fd5b6000805b600254811015610acb57826001600160a01b031660018281548110610aa057fe5b6000918252602090912001546001600160a01b03161415610ac357809150610acb565b600101610a7f565b506001600160a01b0382166000908152602081905260409020805460ff1916905560025460018054909160001901908110610b0257fe5b600091825260209091200154600180546001600160a01b039092169183908110610b2857fe5b9060005260206000200160006101000a8154816001600160a01b0302191690836001600160a01b031602179055506001805480610b6157fe5b600082815260208120820160001990810180546001600160a01b03191690559182019092556002805490910190556040516001600160a01b0384169185917f7126bef88d1149ccdff9681ed5aecd3ba5ae70c96517551de250af09cebd1a0b9190a3505050565b600082610bd757506000610bf0565b5081810281838281610be557fe5b0414610bf057600080fd5b9291505056fea265627a7a72315820c6573af0b3b7c3247487ee9ed708b6a164b470113ea868682e45ba0881245abc64736f6c63430005110032",
      "storage": {
        "0x0000000000000000000000000000000000000000000000000000000000000001": "0x0000000000000000000000000000000000000000000000000000000000000003",
        "0x0000000000000000000000000000000000000000000000000000000000000002": "0x0000000000000000000000000000000000000000000000000000000000000003",
        "0x0000000000000000000000000000000000000000000000000000000000000003": "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x0000000000000000000000000000000000000000000000000000000000000004": "0x0000000000000000000000000000000000000000000000000000000000000002",
        "0x0000000000000000000000000000000000000000000000000000000000000005": "0x0000000000000000000000000000000000000000000000000000000000000022",
        "0x3fe2f293acf503f2994aab2857f9ce3851c5247afdec4246158a27ed5cd13758": "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0xa117c3dfb17ad1cecd529456450880871f394ffc6f70447df7adc715089f842f": "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x4044547d2a82db717919acffa778bb537516a0acf915a0d97a6a210209c55fcb": "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0xb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf6": "0x000000000000000000000000f224beff587362a88d859e899d0d80c080e1e812",
        "0xb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf7": "0x00000000000000000000000011360eacdedd59bc433afad4fc8f0417d1fbebab",
        "0xb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf8": "0x00000000000000000000000070bb1fb41c8c42f6ddd53a708e2b82209495e455"
      }
    },
    "0x0000000000000000000000000000000000000022": {
      "balance": "0x0",
      "code": "0x608060405234801561001057600080fd5b50600436106101425760003560e01c80638f283970116100b8578063c7dd11bd1161007c578063c7dd11bd1461067a578063d365a3771461071e578063d87478c3146107bf578063e28d4906146107e8578063ec9ab83c14610805578063f851a440146108bd57610142565b80638f2839701461057d5780639a202d47146105a35780639a307391146105ab5780639f4d9634146105d1578063a07aea1c146105d957610142565b806341433aeb1161010a57806341433aeb146103bd578063435c93da146103ef578063635b27701461046c5780636f91f82f146104925780637284f84d146104c35780638e4668491461057557610142565b806305b2cfbc1461014757806305f41018146101ed57806327f5b35b1461023a5780632f583c89146102e35780633a5381b514610399575b600080fd5b6101eb6004803603602081101561015d57600080fd5b810190602081018135600160201b81111561017757600080fd5b82018360208201111561018957600080fd5b803590602001918460018302840111600160201b831117156101aa57600080fd5b91908080601f0160208091040260200160405190810160405280939291908181526020018383808284376000920191909152509295506108c5945050505050565b005b6102166004803603606081101561020357600080fd5b508035906020810135906040013561090b565b6040518082600281111561022657fe5b60ff16815260200191505060405180910390f35b6102166004803603606081101561025057600080fd5b810190602081018135600160201b81111561026a57600080fd5b82018360208201111561027c57600080fd5b803590602001918460018302840111600160201b8311171561029d57600080fd5b91908080601f0160208091040260200160405190810160405280939291908181526020018383808284376000920191909152509295505082359350505060200135610931565b610387600480360360208110156102f957600080fd5b810190602081018135600160201b81111561031357600080fd5b82018360208201111561032557600080fd5b803590602001918460018302840111600160201b8311171561034657600080fd5b91908080601f01602080910402602001604051908101604052809392919081815260200183838082843760009201919091525092955061096a945050505050565b60408051918252519081900360200190f35b6103a1610985565b604080516001600160a01b039092168252519081900360200190f35b610387600480360360608110156103d357600080fd5b50803590602081013590604001356001600160a01b0316610994565b6103f76109b7565b6040805160208082528351818301528351919283929083019185019080838360005b83811015610431578181015183820152602001610419565b50505050905090810190601f16801561045e5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b6101eb6004803603602081101561048257600080fd5b50356001600160a01b03166109e2565b6104af600480360360208110156104a857600080fd5b5035610a1b565b604080519115158252519081900360200190f35b6104af600480360360608110156104d957600080fd5b810190602081018135600160201b8111156104f357600080fd5b82018360208201111561050557600080fd5b803590602001918460018302840111600160201b8311171561052657600080fd5b91908080601f01602080910402602001604051908101604052809392919081815260200183838082843760009201919091525092955050823593505050602001356001600160a01b0316610a30565b6103f7610a73565b6101eb6004803603602081101561059357600080fd5b50356001600160a01b0316610aa0565b6101eb610b25565b6104af600480360360208110156105c157600080fd5b50356001600160a01b0316610b84565b6103f7610b99565b6101eb600480360360208110156105ef57600080fd5b810190602081018135600160201b81111561060957600080fd5b82018360208201111561061b57600080fd5b803590602001918460208302840111600160201b8311171561063c57600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600092019190915250929550610bc7945050505050565b6101eb6004803603602081101561069057600080fd5b810190602081018135600160201b8111156106aa57600080fd5b8201836020820111156106bc57600080fd5b803590602001918460018302840111600160201b831117156106dd57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600092019190915250929550610cbe945050505050565b6101eb6004803603602081101561073457600080fd5b810190602081018135600160201b81111561074e57600080fd5b82018360208201111561076057600080fd5b803590602001918460208302840111600160201b8311171561078157600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600092019190915250929550610cfd945050505050565b610387600480360360608110156107d557600080fd5b5080359060208101359060400135610ea5565b6103a1600480360360208110156107fe57600080fd5b5035610ec8565b6102166004803603608081101561081b57600080fd5b810190602081018135600160201b81111561083557600080fd5b82018360208201111561084757600080fd5b803590602001918460018302840111600160201b8311171561086857600080fd5b91908080601f01602080910402602001604051908101604052809392919081815260200183838082843760009201919091525092955050823593505050602081013590604001356001600160a01b0316610eef565b6103a1611123565b6000546001600160a01b031633146108dc57600080fd5b60006108e782611132565b90506108f2816111c4565b6000908152600360205260409020805460ff1916905550565b600660209081526000938452604080852082529284528284209052825290205460ff1681565b60008061093d85611132565b6000908152600660209081526040808320968352958152858220948252939093525050205460ff16919050565b600061097582611132565b9050610980816111c4565b919050565b6007546001600160a01b031681565b600460209081526000938452604080852082529284528284209052825290205481565b6040518060400160405280600f81526020016e11115413d4d25517d0d21053939153608a1b81525081565b6000546001600160a01b031633146109f957600080fd5b600780546001600160a01b0319166001600160a01b0392909216919091179055565b60036020526000908152604090205460ff1681565b600080610a3c85611132565b600090815260046020908152604080832087845282528083206001600160a01b038716845290915290205415159150509392505050565b604051806040016040528060118152602001701590531251105513d497d0d21053939153607a1b81525081565b6000546001600160a01b03163314610ab757600080fd5b6001600160a01b038116610aca57600080fd5b600080546040516001600160a01b03808516939216917f7e644d79422f17c01e4894b5f4f588d331ebfa28653d42ae832dc59e38c9798f91a3600080546001600160a01b0319166001600160a01b0392909216919091179055565b6000546001600160a01b03163314610b3c57600080fd5b600080546040516001600160a01b03909116917fa3b62bc36326052d97ea62d63c3d60308ed4c3ea8ac079dd8499f1e9c4f80c0f91a2600080546001600160a01b0319169055565b60026020526000908152604090205460ff1681565b6040518060400160405280601281526020017115d2551211149055d05317d0d2105393915360721b81525081565b6000546001600160a01b03163314610bde57600080fd5b6000805b8251811015610cb957828181518110610bf757fe5b6020908102919091018101516001600160a01b0381166000908152600290925260409091205490925060ff16610cb1576001805480820182557fb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf60180546001600160a01b0319166001600160a01b038516908117909155600081815260026020526040808220805460ff1916909417909355915190917fac6fa858e9350a46cec16539926e0fde25b7629f84b5a72bffaae4df888ae86d91a25b600101610be2565b505050565b6000546001600160a01b03163314610cd557600080fd5b6000610ce082611132565b6000908152600360205260409020805460ff191660011790555050565b6000546001600160a01b03163314610d1457600080fd5b6000805b8251811015610dad57828181518110610d2d57fe5b6020908102919091018101516001600160a01b0381166000908152600290925260409091205490925060ff1615610da5576001600160a01b038216600081815260026020526040808220805460ff19169055517f80c0b871b97b595b16a7741c1b06fed0c6f6f558639f18ccbce50724325dc40d9190a25b600101610d18565b5060005b600154811015610cb95760018181548110610dc857fe5b60009182526020808320909101546001600160a01b0316808352600290915260409091205490925060ff16610e9c57600180546000198101908110610e0957fe5b600091825260209091200154600180546001600160a01b039092169183908110610e2f57fe5b600091825260209091200180546001600160a01b0319166001600160a01b0392909216919091179055600180546000198101908110610e6a57fe5b600091825260209091200180546001600160a01b03191690556001805490610e9690600019830161122a565b50610ea0565b6001015b610db1565b600560209081526000938452604080852082529284528284209052825290205481565b60018181548110610ed557fe5b6000918252602090912001546001600160a01b0316905081565b3360009081526002602052604081205460ff16610f0b57600080fd5b6000610f168661096a565b600081815260046020908152604080832089845282528083206001600160a01b038816845290915290205490915015610f805760405162461bcd60e51b815260040180806020018281038252603381526020018061126b6033913960400191505060405180910390fd5b600081815260046020818152604080842089855282528084206001600160a01b038089168652908352818520899055858552600683528185208a86528352818520898652835281852054868652600584528286208b875284528286208a8752845294829020546007548351631b5f5c8160e31b81526001830196810196909652925160ff909616959094929091169263dafae4089260248082019391829003018186803b15801561103057600080fd5b505afa158015611044573d6000803e3d6000fd5b505050506040513d602081101561105a57600080fd5b5051156110d357600082600281111561106f57fe5b14156110a65760008381526006602090815260408083208a845282528083208984529091529020805460ff191660011790556110d3565b60008381526006602090815260408083208a845282528083208984529091529020805460ff191660021790555b5050600081815260056020908152604080832088845282528083208784528252808320805460010190559282526006815282822087835281528282208683529052205460ff169050949350505050565b6000546001600160a01b031681565b6000816040516020018080602001828103825283818151815260200191508051906020019080838360005b8381101561117557818101518382015260200161115d565b50505050905090810190601f1680156111a25780820380516001836020036101000a031916815260200191505b5092505050604051602081830303815290604052805190602001209050919050565b60008181526003602052604090205460ff16611227576040805162461bcd60e51b815260206004820181905260248201527f41636b6e6f776c656467656d656e743a20696e76616c6964206368616e6e656c604482015290519081900360640190fd5b50565b815481835581811115610cb957600083815260209020610cb991810190830161126791905b80821115611263576000815560010161124f565b5090565b9056fe41636b6e6f776c656467656d656e743a207468652076616c696461746f7220616c72656164792061636b6e6f776c6564676564a265627a7a723158209aed05d74b9840858e5ac5683b5d25d22bbd163af08b24bc1af03219abf0b7d264736f6c63430005110032",
      "storage": {
        "0x0000000000000000000000000000000000000000000000000000000000000000": "0x000000000000000000000000ed4a9f48a62fb6fdcfb45bb00c9f61d1a436e58c",
        "0x0000000000000000000000000000000000000000000000000000000000000001": "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x0000000000000000000000000000000000000000000000000000000000000007": "0x0000000000000000000000000000000000000000000000000000000000000011",
        "0xb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf6": "0x0000000000000000000000000000000000000000000000000000000000000011",
        "0xa4e0f4432e44d027a7b3f953940f096bca7a9bd910297cad2ba7c703c2b799d3": "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0xf60e76f92b2a488ed03e0cd79ddc30e3ebf1976f8894261e7f85c346ea7d0f1d": "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x51ecc4de9dec5e56eeda533002a3799c48bd59218c8ba66e6d1b5af56c02e2b5": "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0xa6ddbdd89aa33000e6eb92d85fcccf53eb95603a5e73f0d31a88a764062af630": "0x0000000000000000000000000000000000000000000000000000000000000001"
      }
    },
    "0x0000000000000000000000000000000000000033": {
      "balance": "0x0",
      "code": "0x608060405234801561001057600080fd5b50600436106100885760003560e01c80639a202d471161005b5780639a202d4714610116578063d936547e1461011e578063f59c370814610144578063f851a4401461017257610088565b80633af32abf1461008d57806347a3ed0c146100c75780635d54e612146100e85780638f283970146100f0575b600080fd5b6100b3600480360360208110156100a357600080fd5b50356001600160a01b0316610196565b604080519115158252519081900360200190f35b6100e6600480360360208110156100dd57600080fd5b503515156101c8565b005b6100b361021c565b6100e66004803603602081101561010657600080fd5b50356001600160a01b0316610225565b6100e66102aa565b6100b36004803603602081101561013457600080fd5b50356001600160a01b0316610309565b6100e66004803603604081101561015a57600080fd5b506001600160a01b038135169060200135151561031e565b61017a610389565b604080516001600160a01b039092168252519081900360200190f35b60025460009060ff16806101c257506001600160a01b03821660009081526001602052604090205460ff165b92915050565b6000546001600160a01b031633146101df57600080fd5b6002805460ff19168215159081179091556040517f01d0151a76b6ade3851c417c9a2511eefa3e319bc884bae10c3dc989e7e8d85e90600090a250565b60025460ff1681565b6000546001600160a01b0316331461023c57600080fd5b6001600160a01b03811661024f57600080fd5b600080546040516001600160a01b03808516939216917f7e644d79422f17c01e4894b5f4f588d331ebfa28653d42ae832dc59e38c9798f91a3600080546001600160a01b0319166001600160a01b0392909216919091179055565b6000546001600160a01b031633146102c157600080fd5b600080546040516001600160a01b03909116917fa3b62bc36326052d97ea62d63c3d60308ed4c3ea8ac079dd8499f1e9c4f80c0f91a2600080546001600160a01b0319169055565b60016020526000908152604090205460ff1681565b6000546001600160a01b0316331461033557600080fd5b6001600160a01b038216600081815260016020526040808220805460ff191685151590811790915590519092917faf367c7d20ce5b2ab6da56afd0c9c39b00ba995263c60292a3e1ee3781fd488591a35050565b6000546001600160a01b03168156fea265627a7a72315820ed0303203e1d12d1308e68c6654bf8d7f5587db47767d55e8f4cf3e0a8d8312664736f6c63430005110032",
      "storage": {
        "0x0000000000000000000000000000000000000000000000000000000000000000": "0x000000000000000000000000ed4a9f48a62fb6fdcfb45bb00c9f61d1a436e58c",
        "0x0784eba0f043780fbed59095817be2808c329ba2819c671df5da4de63ec076ef": "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0xb01d85f65a35ec8b70f659110ed3b4424971d5985334104fc36fb66cdc1d070c": "0x0000000000000000000000000000000000000000000000000000000000000001"
      }
    },
    "0xed4a9f48a62fb6fdcfb45bb00c9f61d1a436e58c": {
      "balance": "0x33b2e3c9fd0803ce8000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "difficulty": "0x7",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x80000000",
  "nonce": "0x0000000000000000",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}

```

**Comment by fwhappy** [comment]
@DNK90 

Thanks, resloved.


But i use snapshot download from https://github.com/axieinfinity/ronin-snapshot .
There is a panic that causes it not to start

INFO [03-13|06:49:17.224] Initialised chain configuration          config="{ChainID: 2020 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 4977778, Odysseus: 10301597, Fenix: 14938103, Muir Glacier: <nil>, Berlin: <nil>, London: <nil>, Arrow Glacier: <nil>, Engine: consortium, Blacklist Contract: 0x313b24994c93FA0471CB4D7aB796b07467041806, Fenix Validator Contract: 0x7f13232Bdc3a010c3f749a1c25bF99f1C053CE70, ConsortiumV2: <nil>, ConsortiumV2.RoninValidatorSet: 0x0000000000000000000000000000000000000000, ConsortiumV2.SlashIndicator: 0x0000000000000000000000000000000000000000, ConsortiumV2.StakingContract: 0x0000000000000000000000000000000000000000, Puffy: <nil>, Buba: <nil>}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xad7028]

goroutine 1 [running]:
math/big.(*Int).Uint64(...)
        math/big/int.go:384
github.com/ethereum/go-ethereum/consensus/consortium/v2.New(0x400117e700, {0x17960b8?, 0x40003ac678}, 0x4002603040, {0x6e, 0x67, 0x5e, 0xe9, 0x76, 0x7, ...}, ...)
        github.com/ethereum/go-ethereum/consensus/consortium/v2/consortium.go:136 +0x98
github.com/ethereum/go-ethereum/consensus/consortium.New(0x400117e700, {0x17960b8, 0x40003ac678}, 0x4000db4f60?, {0x6e, 0x67, 0x5e, 0xe9, 0x76, 0x7, ...})
        github.com/ethereum/go-ethereum/consensus/consortium/main.go:30 +0x70
github.com/ethereum/go-ethereum/eth/ethconfig.CreateConsensusEngine(0x400014ad40?, 0x1b?, 0x2?, {0x0?, 0x0?, 0x46d1ac?}, 0x68?, {0x17960b8?, 0x40003ac678?}, 0x46d8a4?, ...)
        github.com/ethereum/go-ethereum/eth/ethconfig/config.go:220 +0x258
github.com/ethereum/go-ethereum/eth.New(0x40003876c0, 0x4000404a00)
        github.com/ethereum/go-ethereum/eth/backend.go:163 +0x930
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0x0?, 0x4000404a00)
        github.com/ethereum/go-ethereum/cmd/utils/flags.go:1819 +0x138
main.makeFullNode(0x177abe8?)
        github.com/ethereum/go-ethereum/cmd/ronin/config.go:162 +0x1a8
main.geth(0x400049e160)
        github.com/ethereum/go-ethereum/cmd/ronin/main.go:341 +0x9c
gopkg.in/urfave/cli%2ev1.HandleAction({0x127ab80?, 0x15eaa28?}, 0x4000361000?)
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x70
gopkg.in/urfave/cli%2ev1.(*App).Run(0x4000398680, {0x4000132000, 0x16, 0x16})
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x544
main.main()
        github.com/ethereum/go-ethereum/cmd/ronin/main.go:281 +0x50
